spring.application.name=api-gateway
server.port=9090

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

# Eureka — injected at runtime via env var
eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
eureka.client.enabled=true
eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=30